### ISSUE TITLE
Academic Support

### ISSUE THREAD

**Issue by TomasAndersonFang** [liuhuigmail/GrowingBugRepository#31]
Hi,

Thanks for your shared benchmark for APR. I want to add your project to my work as one of the benchmarks, but I downloaded the main branch and found it may have some problems like it doesn't contain `sling_feature` project, but I can get it with the command `defects4j pids`, which may produce the problems, e.g., If I want to extract all bugs in all projects. So could you provide me with a stable version of your project?

Thanks

**Comment by liuhuigmail** [comment]
Thanks for your interest in our dataset. 

We will release (within a couple of dates) a stable version where some state-of-the-art program repair tools have been validated.

**Comment by TomasAndersonFang** [comment]
@liuhuigmail 
That's great!!! Looking forward to it.

**Comment by jiangyanjie** [comment]
Thanks for your interest in our dataset. 

During the construction of the dataset, we removed some bugs after double-checking, and thus some meta information of projects are kept even if all bugs associated with them have been removed. To avoid such misleading info, we strongly suggest to retrieve bugs according to the bug list in README file. 

By the way, If you use growingBugs to evaluate your own bug-fixing approach, we may provide some results of the state-of-the-art bug fixing tools on our dataset. The evaluation was based on version https://github.com/liuhuigmail/GrowingBugRepository/tree/v6

Please feel free to contact with me. Thanks.

**Comment by TomasAndersonFang** [comment]
@jiangyanjie Thank you very much for your support!

> During the construction of the dataset, we removed some bugs after double-checking, and thus some meta information of projects are kept even if all bugs associated with them have been removed. To avoid such misleading info, we strongly suggest to retrieve bugs according to the bug list in README file.

Thanks for your suggestions; it will help me a lot.

> By the way, If you use growingBugs to evaluate your own bug-fixing approach, we may provide some results of the state-of-the-art bug fixing tools on our dataset. The evaluation was based on version https://github.com/liuhuigmail/GrowingBugRepository/tree/v6

It's great news for us. When we finish our project, we may seek further support from you.
