### ISSUE TITLE
How to reproduce the `bug_commit_classification` sub-module?

### ISSUE THREAD

**Issue by Feng-Jay** [liuhuigmail/GrowingBugRepository#39]
Hi! Thanks for this valuable dataset and the tool for extracting patches! Your work leaves a deep impression on me!

For now, I'd like to utilize the bug-mining framework of `GrowingBugRepository` to find more recenet bugs. However, when I exec the `~/framework/bug-mining/initialize-project-and-collect-issues.pl` script, I found the `line-184` start the `bug_commit_classification` sub-module which fine-tuning a classifier based on `robeta-base`. 

However, I found there is no training data under the `framework/bug-mining/bug_commit_classification/data/` directory and the pre-trained parameters which loaded at the `Line-118` of `framework/bug-mining/bug_commit_classification/code/run_model.py` is also not uploaded.

So, could you provide this data to help me with my research? I look forward to your prompt reply 🤩 !

**Comment by jiangyanjie** [comment]
Thanks for your interest in our dataset.

We uploaded the training data under the `framework/bug-mining/bug_commit_classification/data/`
