### ISSUE TITLE
There is no `load_cross_validation_split` method in `dataloader`

### ISSUE THREAD

**Issue by Feng-Jay** [liuhuigmail/GrowingBugRepository#41]
Hi! Thanks for your prompt reply #39 !

After getting these data, I executed `framework/bug-mining/bug_commit_classification/code/preprocess.py` to process them. However, it reported an error `ImportError: cannot import name 'load_cross_validation_split' from 'dataloader'`. I have checked the `framework/bug-mining/bug_commit_classification/code/dataloader.py` and found there is no such method defined in this file.

Is there a problem with my workflow? Or is there might be an issue with inconsistent code versions here? Can you help me with that?

I look forward to your prompt reply! 😃

**Comment by jiangyanjie** [comment]
We update the dataloader.
